name: Count Clicks

on:
  schedule:
    - cron: "*/15 * * * *" # Vérifie toutes les 15 minutes
  workflow_dispatch: # Permet de le lancer manuellement

jobs:
  track-clicks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Créer des logs d'exemple (simulation)
        run: |
          mkdir logs
          # ⚠️ Ici normalement on utiliserait les vrais logs GitHub Pages.
          # Pour tester, on simule des clics dans un fichier logs.
          echo "GET /tracker.gif?person=alice" >> logs/access.log
          echo "GET /tracker.gif?person=alice" >> logs/access.log
          echo "GET /tracker.gif?person=bob" >> logs/access.log

      - name: Mettre à jour clicks.json
        run: |
          # Charger clicks.json actuel
          tmpfile=$(mktemp)
          cp clicks.json $tmpfile

          # Parcourir les logs simulés
          while read -r line; do
            if [[ "$line" == *"tracker.gif?person="* ]]; then
              person=$(echo $line | sed -n 's/.*person=\(.*\)/\1/p')
              current=$(jq -r --arg p "$person" '.[$p] // 0' $tmpfile)
              new=$((current + 1))
              jq --arg p "$person" --argjson n $new '.[$p] = $n' $tmpfile > tmp.json && mv tmp.json $tmpfile
            fi
          done < logs/access.log

          mv $tmpfile clicks.json

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add clicks.json
          git commit -m "Update clicks.json"
          git push
